{
  "hash": "0818fd8b65bd1fd2a555bef6b911610b",
  "result": {
    "engine": "jupyter",
    "markdown": "# The Urban Data Toolkit {#sec-toolkit}\n\n> *\"It'll be a great place if they ever finish it.\"*\n> — attributed to O. Henry, on New York\n\n::: {.callout-tip appearance=\"simple\"}\n## Anchor: New York City\n**Dataset** — NYC 311 Service Requests (NYC Open Data): 40+ million complaints — noise, heat, rats, potholes — with timestamps, categories, and coordinates, split across [2020–present](https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2020-to-Present/erm2-nwe9) and [2010–2019](https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-2019/76ig-c548) datasets. Direct download or Socrata API; no key required. *Verified June 2026.*\n:::\n\nDial 311 in New York and a person answers, at any hour, in any of 175 languages. The number exists so that 911 can be reserved for emergencies, which means 311 receives everything else: the neighbor's subwoofer, the radiator that never warmed, the rat observed at leisure in a Brooklyn courtyard. The city logs every call — and every app report and web form — with a timestamp, a category, an agency, and, most of the time, a location. Since 2010 it has published the ledger in full. Forty million grievances, free to anyone, updated daily.\n\nThis is *administrative exhaust*: data produced as a byproduct of running a city rather than for the benefit of researchers. Nobody at 311 is collecting observations for us. They are dispatching rat inspectors. That the resulting table happens to be one of the richest behavioral datasets in urban science is a happy accident — and the accident comes with terms and conditions that this chapter will teach you to read.\n\nThe chapter is a toolbox, but a toolbox demonstrated on a real job, because tool demonstrations without jobs are how manuals put their readers to sleep. By the end you will have asked a live municipal API a question, received two years of the city's complaints in summary, joined them to official geography, and drawn maps honest enough to publish. Every later chapter in this book is a variation on that sequence. Amsterdam, Tokyo, São Paulo: different portals, different quirks, same craft.\n\n## The stack, quickly\n\nThe book's analyses run on the scientific Python stack, and on the principle that you should know your tools well enough to distrust them in the right places.\n\n**pandas** is the workhorse: tables in, tables out, with an API that has grown by accretion since 2008 and shows it. You will sometimes find three ways to do a thing and one of them deprecated; this is the price of working in a living language, and it is worth paying. **GeoPandas** is pandas sent to geography school — every row gains a geometry, and suddenly `merge` has a spatial cousin called `sjoin`. Underneath sit **shapely** (the geometry engine) and **pyproj** (the projection engine), which you will rarely call directly and should be glad exist. **matplotlib** draws everything in this book. It is verbose, old-fashioned, and capable of great beauty, three qualities it shares with the city we are about to study. **requests** talks to the internet.\n\nThe geospatial stack once had a deserved reputation for installation grief. The reputation outlived the grief by about a decade; modern wheels have retired most of it. Appendix A handles setup, and the few packages each chapter adds will be introduced when they earn their entrance.\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Chapter setup\"}\nfrom pathlib import Path\n\nimport geopandas as gpd\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport pandas as pd\nimport requests\n\nfrom book_style import set_style, PALETTE, NAVY, GOLD, TEAL\n\nset_style()\nSNAP = Path(\"data/snapshots/nyc_311\")\n```\n:::\n\n\nOne convention before we begin. Every dataset in this book is fetched through a small helper that checks for a local copy first:\n\n::: {#cached-helper .cell execution_count=2}\n``` {.python .cell-code}\ndef cached(path: Path, fetch):\n    \"\"\"Read a snapshot if it exists; otherwise fetch, save, and return it.\"\"\"\n    if path.exists():\n        return pd.read_csv(path)\n    df = fetch()\n    path.parent.mkdir(parents=True, exist_ok=True)\n    df.to_csv(path, index=False)\n    return df\n```\n:::\n\n\nEight lines, no cleverness. They are the difference between an analysis that works this year and an analysis that works when a reader runs it in five, after the portal has reorganized twice. We will have more to say about this in @sec-toolkit-repro; for now, simply notice that every fetch in this chapter passes through it — or through the same check written out longhand, where geometry demands its own file format.\n\n## Portals and APIs: getting the data\n\nOpen data portals are young. The United States launched data.gov in 2009; New York passed its Open Data Law in 2012, requiring every city agency to publish its public data on a single portal — and, pointedly, to publish it \"without registration requirement, license requirement, or usage restrictions.\" Several hundred cities followed, atop a small oligopoly of platforms: **Socrata** (now Tyler Technologies, hosting New York and Chicago), **CKAN** (open-source, hosting Mexico City and much of Europe), and **ArcGIS Hub** (Esri's entry, common in mid-sized American cities). Learn one and the others feel familiar, the way a traveler who can navigate one airport can navigate them all.\n\nA Socrata dataset is identified by a nine-character code — `erm2-nwe9` for the 311 requests since 2020 — and answers at a predictable address. Ask politely and you receive JSON:\n\n::: {#cell-first-touch .cell execution_count=3}\n``` {.python .cell-code}\nurl = \"https://data.cityofnewyork.us/resource/erm2-nwe9.json\"\nsample = cached(\n    SNAP / \"sample_rows.csv\",\n    lambda: pd.DataFrame(requests.get(url, params={\"$limit\": 3}, timeout=60).json()),\n)\nsample[[\"created_date\", \"complaint_type\", \"borough\", \"status\"]]\n```\n\n::: {#first-touch .cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>created_date</th>\n      <th>complaint_type</th>\n      <th>borough</th>\n      <th>status</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2026-06-09T02:15:22.000</td>\n      <td>Street Condition</td>\n      <td>QUEENS</td>\n      <td>Open</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2026-06-09T02:06:15.000</td>\n      <td>Noise - Street/Sidewalk</td>\n      <td>BRONX</td>\n      <td>In Progress</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2026-06-09T02:06:02.000</td>\n      <td>Noise - Residential</td>\n      <td>BROOKLYN</td>\n      <td>In Progress</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThree complaints, plucked from forty million. The `$limit` parameter belongs to **SoQL**, the portal's query language — SQL spoken with a slight accent. You can `$select`, `$where`, `$group`, and `$order`, and the entire grammar can be learned in an afternoon. An *app token* (free, instant) lifts the rate limits; at this book's volumes you will not need one, though registering is good manners if you script against a portal regularly.\n\nThe beginner's instinct is to download everything and filter at home. Resist it. The full 311 table runs to tens of gigabytes, and your question — say, *how do complaints vary across the year?* — has an answer that fits in kilobytes.\n\nNever download what you can summarize at the source.\n\n::: {#cell-type-totals .cell execution_count=4}\n``` {.python .cell-code}\ndef soql(dataset: str, **query):\n    \"\"\"One page of a SoQL query, as a DataFrame.\"\"\"\n    url = f\"https://data.cityofnewyork.us/resource/{dataset}.json\"\n    query.setdefault(\"$limit\", 50_000)\n    r = requests.get(url, params=query, timeout=120)\n    r.raise_for_status()\n    return pd.DataFrame(r.json())\n\ntotals = cached(\n    SNAP / \"type_totals.csv\",\n    lambda: soql(\n        \"erm2-nwe9\",\n        **{\n            \"$select\": \"complaint_type, count(*) as n\",\n            \"$where\": \"created_date >= '2024-01-01' and created_date < '2026-01-01'\",\n            \"$group\": \"complaint_type\",\n            \"$order\": \"n DESC\",\n        },\n    ),\n)\ntotals[\"n\"] = totals[\"n\"].astype(int)\ntotals.head(10)\n```\n\n::: {#type-totals .cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>complaint_type</th>\n      <th>n</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Illegal Parking</td>\n      <td>1082985</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Noise - Residential</td>\n      <td>842645</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>HEAT/HOT WATER</td>\n      <td>580696</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Blocked Driveway</td>\n      <td>342915</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Noise - Street/Sidewalk</td>\n      <td>336050</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>UNSANITARY CONDITION</td>\n      <td>238598</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Water System</td>\n      <td>143307</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Street Condition</td>\n      <td>141489</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Abandoned Vehicle</td>\n      <td>138229</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>PLUMBING</td>\n      <td>135450</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe server did the counting; seven million complaints from two years of city life crossed the wire as 203 rows, one per category. The ranking itself is already sociology. *Illegal parking* dominates at over a million reports — half a million a year, New York's truly inexhaustible resource — with *residential noise* (843,000) and *heat* (581,000) behind it, and the list runs down through blocked driveways, street noise, and unsanitary conditions before reaching the long tail of the merely occasional. The rat, for all its press, sits at #25.\n\nCategories are where the first bodies are buried. `HEAT/HOT WATER` is shouting in capitals because it migrated from a legacy system; `Noise` arrives in eight flavors (residential, street, commercial, vehicle, park, helicopter, an unmodified `Noise`, and — the city being what it is — `House of Worship`); and the same pothole may be a `Street Condition` to one intake channel and a `Highway Condition` to another. Names also die and are reborn: the 2010s archive carries both `Dead Tree` and its successor `Dead/Dying Tree`, running side by side for years until the older of the two stopped, unannounced. Administrative categories encode administrative history, not analytical convenience. The first hour with any new dataset is properly spent on this kind of archaeology — counting categories, reading the data dictionary, discovering which fields are real and which are vestigial.\n\nWith aggregation in hand we can ask the question that motivates the chapter's first real figure: what does a year of complaint look like?\n\n::: {#fetch-daily .cell execution_count=5}\n``` {.python .cell-code}\nTYPES = [\n    \"Noise - Residential\", \"Noise - Street/Sidewalk\", \"Illegal Fireworks\",\n    \"HEAT/HOT WATER\", \"Snow or Ice\", \"Rodent\",\n    \"Illegal Parking\", \"Damaged Tree\", \"Dead/Dying Tree\",\n]\n\ndaily = cached(\n    SNAP / \"daily_by_type.csv\",\n    lambda: soql(\n        \"erm2-nwe9\",\n        **{\n            \"$select\": \"date_trunc_ymd(created_date) as day, complaint_type, count(*) as n\",\n            \"$where\": (\n                \"created_date >= '2024-01-01' and created_date < '2026-01-01' and \"\n                \"complaint_type in (\"\n                + \", \".join(f\"'{t}'\" for t in TYPES)\n                + \")\"\n            ),\n            \"$group\": \"day, complaint_type\",\n            \"$order\": \"day\",\n        },\n    ),\n)\ndaily[\"day\"] = pd.to_datetime(daily[\"day\"])\ndaily[\"n\"] = daily[\"n\"].astype(int)\n```\n:::\n\n\n::: {#cell-fig-seasons .cell execution_count=6}\n``` {.python .cell-code code-fold=\"true\"}\nfig, axes = plt.subplots(3, 3, figsize=(9.5, 6.5), sharex=True)\nfor ax, ctype in zip(axes.flat, TYPES):\n    s = (\n        daily.query(\"complaint_type == @ctype\")\n        .set_index(\"day\")[\"n\"]\n        .asfreq(\"D\", fill_value=0)\n        .rolling(7, center=True)\n        .mean()\n    )\n    ax.fill_between(s.index, s, color=NAVY, alpha=0.85, lw=0)\n    ax.set_title(ctype, fontsize=9.5, loc=\"left\", fontweight=\"normal\")\n    ax.set_xlim(pd.Timestamp(\"2024-01-01\"), pd.Timestamp(\"2026-01-01\"))\n    ax.set_yticks([])\n    ax.grid(False)\n\nticks = pd.date_range(\"2024-01-01\", \"2026-01-01\", freq=\"6MS\")\nfor ax in axes[-1]:\n    ax.set_xticks(ticks, [t.strftime(\"%b %Y\") for t in ticks], fontsize=8.5)\n\ndef season_mark(ax, when, label):\n    \"\"\"A dated tick on one panel, in that panel's own scale.\"\"\"\n    ax.axvline(pd.Timestamp(when), color=GOLD, lw=0.9, ymax=0.8)\n    ax.text(pd.Timestamp(when), 0.86, label, transform=ax.get_xaxis_transform(),\n            fontsize=8, fontstyle=\"italic\", ha=\"center\", color=\"#6b7a8f\")\n\nseason_mark(axes[0, 2], \"2025-07-04\", \"July 4\")\nseason_mark(axes[1, 0], \"2025-10-01\", \"heat season opens\")\nfig.suptitle(\"The city's year, told in complaints\", x=0.01, ha=\"left\", fontsize=13, fontweight=\"bold\")\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![Two years of daily 311 complaints, nine types, 7-day means. Each panel is scaled to its own maximum; the shape, not the level, is the story. Rows: sound, weather, the street itself.](02-the-urban-data-toolkit_files/figure-html/fig-seasons-output-1.png){#fig-seasons}\n:::\n:::\n\n\nThe city has seasons the way a body has a pulse. Heat complaints switch on with the law — \"heat season,\" when landlords must supply it, opens October first, and the curve flexes upward that very day — then ride the thermometer to a midwinter crest twenty-odd times the August floor. Fireworks complaints are a flat line with one volcanic week around the Fourth of July. The two noise types disagree about the calendar: street and sidewalk noise crests at the June solstice and all but vanishes in January, while residential noise — the subwoofer through the wall — runs at its highest sustained levels in the cold months, when life moves indoors, and spikes hardest on one September weekend whose cause the table alone cannot tell you. Rats prefer summer. Illegal parking, the city's base load, scarcely has a season at all. Snow complaints track storms with the fidelity of a seismograph, and the two tree types tell one story on two clocks: dead and dying trees accumulate gently through the leafy months, while damaged trees spike overnight, whenever wind visits. None of this is surprising once seen, and all of it had to be seen to be believed — which is the figure's argument: before any model, *look*.\n\n## Shapes of the city\n\nA complaint without a place is barely a complaint, and the 311 table obliges with latitude and longitude for most rows. But coordinates alone answer no urban question. *Which neighborhood is that rat in?* requires geography to compare against — and a decision about what \"neighborhood\" means, which in New York is a question with theological depth. We will use the city's official compromise: **Neighborhood Tabulation Areas**, 262 zones built from census blocks for the 2020 count, large enough for statistics and small enough to mean something to a resident.\n\n::: {#cell-fetch-geo .cell execution_count=7}\n``` {.python .cell-code}\nnta_path = SNAP / \"nta_2020.geojson\"\nif not nta_path.exists():\n    r = requests.get(\n        \"https://data.cityofnewyork.us/api/geospatial/9nt8-h7nd\",\n        params={\"method\": \"export\", \"format\": \"GeoJSON\"},\n        timeout=300,\n    )\n    nta_path.parent.mkdir(parents=True, exist_ok=True)\n    nta_path.write_text(r.text)\nntas = gpd.read_file(nta_path)\n\nrats = cached(\n    SNAP / \"rat_sightings.csv\",\n    lambda: soql(\n        \"erm2-nwe9\",\n        **{\n            \"$select\": \"unique_key, created_date, borough, latitude, longitude\",\n            \"$where\": (\n                \"created_date >= '2025-01-01' and created_date < '2026-01-01' \"\n                \"and complaint_type = 'Rodent' and descriptor = 'Rat Sighting' \"\n                \"and latitude IS NOT NULL\"\n            ),\n        },\n    ),\n)\nrats = gpd.GeoDataFrame(\n    rats,\n    geometry=gpd.points_from_xy(rats.longitude.astype(float), rats.latitude.astype(float)),\n    crs=\"EPSG:4326\",\n)\nlen(rats)\n```\n\n::: {#fetch-geo .cell-output .cell-output-display execution_count=7}\n```\n19846\n```\n:::\n:::\n\n\nA year of rat sightings — 19,846 of them, each one a point. Before joining points to polygons, a word about the coordinate systems they live in, because this is where geographic analysis quietly goes wrong.\n\nLatitude and longitude are angles on a spheroid, not positions on a plane. Software will happily treat them as x and y — and will then compute \"distances\" in degrees, an honest-sounding unit that is 30% longer north–south than east–west at New York's latitude. Every serious operation wants a *projected* coordinate system: a defined flattening of some patch of the earth onto a plane, with known, chosen distortions. A projection is a treaty with the globe: you cannot preserve area, shape, distance, and direction at once, so you sign away the ones your problem can afford to lose.\n\nWeb Mercator (`EPSG:3857`), the projection of every slippy web map, signs away area — catastrophically at the poles, mildly but really at 40°N. For navigation this is the right treaty; for measuring neighborhoods it is the wrong one. New York analysis belongs in the New York–Long Island State Plane system (`EPSG:2263`), a projection so local that its distortions are smaller than surveying error. That it measures in feet is a regional eccentricity the reader is invited to enjoy.\n\n::: {#cell-spatial-join .cell execution_count=8}\n``` {.python .cell-code}\nntas = ntas.to_crs(\"EPSG:2263\")\nrats = rats.to_crs(\"EPSG:2263\")\n\njoined = gpd.sjoin(rats, ntas[[\"ntaname\", \"geometry\"]], how=\"inner\", predicate=\"within\")\nby_nta = joined.groupby(\"ntaname\").size().rename(\"sightings\")\nntas = ntas.merge(by_nta, on=\"ntaname\", how=\"left\").fillna({\"sightings\": 0})\nby_nta.sort_values(ascending=False).head(8)\n```\n\n::: {#spatial-join .cell-output .cell-output-display execution_count=8}\n```\nntaname\nHighbridge                   561\nUpper West Side (Central)    509\nHarlem (North)               491\nCrown Heights (North)        464\nBedford-Stuyvesant (East)    462\nUpper East Side-Yorkville    455\nBedford-Stuyvesant (West)    441\nHarlem (South)               420\nName: sightings, dtype: int64\n```\n:::\n:::\n\n\nThe spatial join — point in polygon, twenty thousand times — runs in under a second and would have been a doctoral labor in 1970. Each sighting now knows its neighborhood; each neighborhood, its count. It remains only to draw the result without lying, which is harder than it sounds.\n\n## A visual grammar for urban data\n\nThis book takes visualization as seriously as estimation, on the grounds that more readers will be persuaded by your maps than by your standard errors — a fact about audiences that confers an obligation on you. The grammar below is short, and every map in the book obeys it.\n\n**Normalize, and argue for the denominator.** Here is the rat map drawn naively, as raw counts:\n\n::: {#cell-fig-rat-naive .cell execution_count=9}\n``` {.python .cell-code code-fold=\"true\"}\nax = ntas.plot(column=\"sightings\", cmap=\"book_seq\", legend=True, figsize=(7.5, 7),\n               edgecolor=\"#dedacc\", linewidth=0.25)\nax.set_axis_off()\nax.set_title(\"Rat sightings, 2025 — raw counts\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Rat sightings by neighborhood, raw counts. Every large or populous neighborhood gets a head start, so the map is part census, part rats — with no way to tell which is which.](02-the-urban-data-toolkit_files/figure-html/fig-rat-naive-output-1.png){#fig-rat-naive}\n:::\n:::\n\n\nA choropleth of raw counts is a population map in costume. Big, dense neighborhoods generate more of nearly everything — rats, noise, weddings — so the unnormalized map repeats the census and calls it analysis. Divide by *something* before you color a polygon. Divide by what? That is an argument, not a reflex: sightings per resident treats rats as a per-person experience; sightings per square kilometer treats them as a property of land. For an outdoor phenomenon reported by passers-by, area is the better-fitting denominator — and the per-capita version, with its own merits, is yours in the chapter's exercises.\n\n::: {#cell-fig-rat-density .cell execution_count=10}\n``` {.python .cell-code code-fold=\"true\"}\nfrom book_style import note\n\n# EPSG:2263 measures in feet; convert to km² for civilized units\nntas[\"km2\"] = ntas.geometry.area / (3280.84**2)\nntas[\"per_km2\"] = ntas[\"sightings\"] / ntas[\"km2\"]\n\nax = ntas.plot(column=\"per_km2\", cmap=\"book_seq\", legend=True, figsize=(7.5, 7),\n               edgecolor=\"#dedacc\", linewidth=0.25)\nx0, y0, x1, y1 = ntas.total_bounds\nfor i, (_, row) in enumerate(ntas.nlargest(3, \"per_km2\").iterrows()):\n    c = row.geometry.centroid\n    note(ax, f\"{row.ntaname} — {row.per_km2:.0f}/km²\",\n         (c.x, c.y), (x0 + 4_000, y1 - 30_000 * i - 8_000))\nax.set_axis_off()\nax.set_title(\"Rat sightings per km², 2025\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The same data, normalized by land area, the three leading neighborhoods labeled. Now the map says something the census did not already say.](02-the-urban-data-toolkit_files/figure-html/fig-rat-density-output-1.png){#fig-rat-density}\n:::\n:::\n\n\nThe density map has a geography the raw map only hinted at. Rat country is the old, dense city: a continuous stretch of upper Manhattan — Harlem, Hamilton Heights, both Upper Sides — and the brownstone belt of Brooklyn, with the South Bronx joining in. Manhattan and Brooklyn split eighteen of the twenty densest neighborhoods between them, nine apiece. And Highbridge in the Bronx manages to top *both* maps from barely more than a square kilometer — 561 sightings, 463 per km² — a distinction no neighborhood campaigns for. The raw map buried that fact under the sheer acreage of the outer boroughs; the normalized map is the one a rodent-control budget should read.\n\n**Choose class breaks in the open.** A choropleth does not show your data; it shows your data after a classifier has had its way. The same density column, cut three ways:\n\n::: {#cell-fig-classification .cell execution_count=11}\n``` {.python .cell-code code-fold=\"true\"}\nimport mapclassify\n\nschemes = [\"equal_interval\", \"quantiles\", \"fisher_jenks\"]\nfig, axes = plt.subplots(1, 3, figsize=(10.5, 4.6))\nfor ax, scheme in zip(axes, schemes):\n    ntas.plot(column=\"per_km2\", scheme=scheme, k=5, cmap=\"book_seq\", ax=ax,\n              legend=False, edgecolor=\"#dedacc\", linewidth=0.2)\n    ax.set_axis_off()\n    ax.set_title(scheme.replace(\"_\", \" \"), fontsize=11)\nfig.suptitle(\"The classifier is part of the message\", x=0.01, ha=\"left\", fontsize=13, fontweight=\"bold\")\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![One dataset, three classifications. Equal intervals surrender the map to outliers; quantiles manufacture drama from dull differences; Fisher–Jenks looks for the data's own seams.](02-the-urban-data-toolkit_files/figure-html/fig-classification-output-1.png){#fig-classification}\n:::\n:::\n\n\nNone of the three is wrong; each answers a different question, and the sin is letting a default answer it for you. My habit: quantiles for ranking talk, equal intervals for magnitude talk, Fisher–Jenks when the data have genuine clusters — and the scheme named in the caption, always, so the reader can object.\n\n**Prefer small multiples to spectacle.** The nine-panel seasons figure earlier carried eighteen thousand numbers without strain because each panel asked one question. The same data as an animation would have been more impressive and less informative — a trade this book refuses on principle. (The web edition allows itself interactivity when it adds an *operation*, like hovering for a neighborhood's name. Decoration animates; instruments respond.)\n\n**Label on the figure, not beside it.** Legends ask the reader's eyes to commute. When a line can carry its own name, it should — you will find the helper `book_style.note` doing this throughout.\n\nOne rhythm figure closes the tour, because it introduces a display we will use in every sensor chapter: the week as a grid.\n\n::: {#cell-fig-rhythms .cell execution_count=12}\n``` {.python .cell-code code-fold=\"true\"}\nrhythms = cached(\n    SNAP / \"rhythms.csv\",\n    lambda: soql(\n        \"erm2-nwe9\",\n        **{\n            \"$select\": (\n                \"complaint_type, date_extract_dow(created_date) as dow, \"\n                \"date_extract_hh(created_date) as hour, count(*) as n\"\n            ),\n            \"$where\": (\n                \"created_date >= '2024-01-01' and created_date < '2026-01-01' and \"\n                \"complaint_type in ('Noise - Residential', 'Rodent')\"\n            ),\n            \"$group\": \"complaint_type, dow, hour\",\n        },\n    ),\n)\nrhythms[[\"dow\", \"hour\", \"n\"]] = rhythms[[\"dow\", \"hour\", \"n\"]].astype(int)\n\ndays = [\"Sun\", \"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\"]\nfig, axes = plt.subplots(1, 2, figsize=(10, 3.6))\nfor ax, ctype in zip(axes, [\"Noise - Residential\", \"Rodent\"]):\n    grid = (\n        rhythms.query(\"complaint_type == @ctype\")\n        .pivot_table(index=\"dow\", columns=\"hour\", values=\"n\")\n        .reindex(index=range(7), columns=range(24))\n    )\n    im = ax.imshow(grid, aspect=\"auto\", cmap=\"book_seq\")\n    ax.set_yticks(range(7), days)\n    ax.set_xticks([0, 6, 12, 18, 23], [\"12am\", \"6am\", \"noon\", \"6pm\", \"11pm\"])\n    ax.set_title(ctype, fontsize=11)\n    ax.grid(False)\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![When New York complains: average complaints by hour and weekday, 2024–2025. Noise lives on weekend nights; rats keep business hours.](02-the-urban-data-toolkit_files/figure-html/fig-rhythms-output-1.png){#fig-rhythms}\n:::\n:::\n\n\nThe complaint line is a sensor wrapped around the city's habits. The loudest cell in the noise grid is Saturday at eleven at night, and the block around it — Friday and Saturday nights, spilling past Sunday's small hours — carries the whole figure. The rat grid is its negative: the weekend's parties are reported in real time, but the weekend's rats wait politely for Monday at ten in the morning, when the reporting week opens. Which raises a question the chapter has been postponing.\n\n::: {.callout-note}\n## What does a complaint measure?\n\nA 311 record is the conjunction of two events: a condition occurred, and somebody reported it. The dataset cannot tell them apart, and the somebody is not drawn at random. Boston's equivalent system, studied by Daniel O'Brien and colleagues, shows reporting propensity varying block by block with homeownership, language, and trust in government; Kontokosta and Hong find the same complaint in New York filed at different rates by demographic context — under-reporting in some immigrant neighborhoods, hair-trigger reporting in gentrifying ones. The rat map is a map of rats *and* of the propensity to report rats, in proportions that vary across the city.\n\nThis does not make the data worthless; it makes the data a measure of something slightly different from its label. 311 measures the demand for government, which is neither the need for it nor the supply of it. Chapter 5 returns to this with formal tools, and Chapter 14 with sharper politics. For now, adopt the habit: for every administrative dataset, ask what behavior had to occur for a row to exist.\n:::\n\n## Reproducibility and the snapshot discipline {#sec-toolkit-repro}\n\nIn December 2025, with no warning that anyone noticed, the 311 dataset split in two. The identifier `erm2-nwe9`, which had meant \"2010 to present\" for a decade, came to mean \"2020 to present\"; the first ten years moved to a new address. Every script in the world that queried the old identifier kept running — silently, on a truncated decade. No error was raised. None ever would be.\n\nThis is the ordinary weather of open data. Portals migrate platforms, agencies rename categories, datasets are split, deprecated, \"improved.\" The 2026 URL in a 2024 paper resolves to a different table or to nothing. Against this, the book practices what it preaches as the *snapshot discipline*:\n\n1. **Every fetch lands in a file** (`data/snapshots/`), and analysis code prefers the file. You saw `cached()` enforcing this all chapter.\n2. **Every snapshot carries a manifest** — source, query, date, license, row count — so its provenance survives the portal's amnesia. The repository's `data/snapshots/*/MANIFEST.md` files are the pattern.\n3. **The environment is pinned** (`requirements.txt`), because an analysis is code *and* dependencies, and the second rots faster.\n4. **Rendered results are frozen** alongside the source, so the published book reflects an execution that actually happened, not one presumed to be repeatable.\n\nThe discipline costs a few minutes per dataset. It buys something close to immortality for the analysis — and, less grandly, it is why every figure in this chapter will still build the week you read this, whatever the portal has done in the meantime.\n\nA toolkit chapter is the throat-clearing of a methods book, and this one is nearly done clearing. But notice what you now hold: you can ask any of several hundred cities' portals a question in their own language, receive the answer summarized, place it on the earth in a defensible projection, color it without propaganda, and preserve the whole transaction against decay. The rest of the book is this loop with better questions.\n\nAsk the city; receive a table; treat it with suspicion; draw it so a stranger can check you.\n\n## Exercises {#sec-toolkit-exercises .unnumbered}\n\n1. **Your nine panels.** Choose nine complaint types we did not plot and reproduce the seasons figure. At least three should surprise a non–New Yorker; write a sentence per panel saying what drives the shape, and flag the panel where you are least confident the driver is real.\n2. **The other decade.** The 2010–2019 archive lives at `76ig-c548`. Pull residential-noise rhythms for 2015 and compare the Saturday-night peak with 2025's. What changed — the noise, or the reporting? Defend your answer with one further query of your choosing.\n3. **The per-capita rat.** Join NTA population (the portal's census tables, or Appendix B's pointers) and redraw the density map per thousand residents. Mind the vintages: the portal's NTA demographics are keyed to *2010* NTA codes, and your boundaries are 2020's — the crosswalk is part of the exercise. Identify two neighborhoods whose rank moves sharply between denominators, and argue which map a Health Department exterminator should trust. There is a defensible answer and it is not \"both.\"\n4. **The landmine hunt.** This dataset contains at least one of each: a duplicated unique key, a complaint created after it was closed, and a coordinate in the Atlantic. Find one instance of anything comparably wrong, document it as a manifest note, and state what analyses it would and would not poison.\n5. **Mercator's bill.** Compute each borough's area in EPSG:4326 (pretending degrees are meters), EPSG:3857, and EPSG:2263. Report the worst percentage error and one published map you suspect of paying it.\n\n## Further reading {.unnumbered}\n\n- **O'Brien, *The Urban Commons* (2018).** The deepest study of what 311-style data measures, built on Boston's system; the source of this chapter's caution about reporters versus conditions.\n- **Kontokosta & Hong, \"Bias in smart-city governance\" (2021).** Quantifies socioeconomic gradients in 311 reporting across New York — required before you regress anything on complaint counts.\n- **Tufte, *The Visual Display of Quantitative Information* (1983).** The grammar behind this book's grammar; read it for the worked demolitions of bad graphics.\n- **The SoQL documentation** (dev.socrata.com). An afternoon here pays for itself within the week.\n- **Wilson et al., \"Good enough practices in scientific computing\" (2017).** The reproducibility discipline, stated for a general scientific audience.\n\n",
    "supporting": [
      "02-the-urban-data-toolkit_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}