{
  "hash": "024857d7643ad006ae2ef15a3dbad878",
  "result": {
    "engine": "jupyter",
    "markdown": "# Statistical Foundations {#sec-stats}\n\n> *\"I have reduced several great confused Volumes into a few perspicuous Tables.\"*\n> — John Graunt, *Natural and Political Observations upon the Bills of Mortality* (1662)\n\n::: {.callout-tip appearance=\"simple\"}\n## Anchor: Amsterdam\n**Dataset** — [Inside Airbnb: Amsterdam](https://insideairbnb.com/amsterdam/): quarterly scrapes of every listing on the platform — price, location, attributes, reviews — published CC BY 4.0. Only the trailing year stays freely downloadable, so the book pins and mirrors the scrape of 11 September 2025: 10,480 listings across the city's 22 districts. Joined with neighborhood population from the [CBS Wijk- en Buurtkaart](https://www.cbs.nl/nl-nl/dossier/nederland-regionaal/geografische-data) (Statistics Netherlands, CC BY 4.0). *Verified June 2026.*\n:::\n\nSomewhere in Amsterdam there is a one-bedroom apartment listed at €80,018 a night. Two of them, in fact — the same price to the euro, which tells you the number is not a price at all but a barricade: the host has somewhere better to be, and the listing is parked where no rational tourist will follow. Nobody will ever pay it. The platform records it anyway, and so the figure sits in the dataset with the same standing as the €61 houseboat berth in Noord, waiting to do to your arithmetic what it was designed to do to bookings.\n\nStatistics is taught here the way cities actually serve it: skewed, heavy-tailed, spatially entangled, and politically charged. Amsterdam's short-term rental market — among the most contested in Europe, capped, registered, and litigated for a decade — supplies the raw material. We will describe distributions whose mean has been kidnapped, measure inequality and find that the answer depends on the question, learn what uncertainty means when the data are not a sample but the whole platform, run our first hypothesis tests — traps and all — and build the book's first regression: *Regression I*, whose sequel arrives when space enters the model in @sec-spatial. Along the way we answer a question with a number attached: what, exactly, is a canal view worth?\n\n::: {#cell-setup .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Chapter setup\"}\nfrom pathlib import Path\n\nimport geopandas as gpd\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport pandas as pd\n\nfrom book_style import set_style, note, PALETTE, NAVY, GOLD, TEAL, BRICK\n\nset_style()\nrng = np.random.default_rng(0)\nSNAP = Path(\"data/snapshots/amsterdam_airbnb\")\n\nlistings = pd.read_parquet(SNAP / \"listings.parquet\")\nareas = gpd.read_file(SNAP / \"areas.geojson\")\npopulation = pd.read_csv(SNAP / \"area_population.csv\")\n\nprice = listings.price.dropna()\nf\"{len(listings):,} listings, {len(price):,} with a price\"\n```\n\n::: {#setup .cell-output .cell-output-display execution_count=1}\n```\n'10,480 listings, 5,874 with a price'\n```\n:::\n:::\n\n\nHalf the listings carry no price. That is not corruption; it is meaning. Inside Airbnb records the displayed nightly rate, and a listing with no bookable nights in the scrape window displays none. The 5,874 priced listings are the market *as offered that week* — a distinction we will need again when we ask what population this data represents.\n\n## Urban distributions and their heavy tails\n\n::: {#cell-tails-numbers .cell execution_count=2}\n``` {.python .cell-code}\nmean, median = price.mean(), price.median()\ntrimmed = price.sort_values().iloc[len(price) // 10 : -len(price) // 10].mean()\npd.Series({\n    \"mean\": mean, \"median\": median, \"10% trimmed mean\": trimmed,\n    \"share of listings below the mean\": (price < mean).mean(),\n    \"share of asking revenue in the top 1%\": price.nlargest(len(price) // 100).sum() / price.sum(),\n}).round(3)\n```\n\n::: {#tails-numbers .cell-output .cell-output-display execution_count=2}\n```\nmean                                     336.785\nmedian                                   222.000\n10% trimmed mean                         236.135\nshare of listings below the mean           0.793\nshare of asking revenue in the top 1%      0.257\ndtype: float64\n```\n:::\n:::\n\n\nThe mean nightly price is €337. The median is €222. The mean of the middle 80% — throw away the cheapest tenth and the dearest tenth — is €236, which is to say that the ordinary listing agrees with the median and the mean has been pulled €100 up-market by a handful of barricades and penthouses. Nearly four listings in five are cheaper than average.\n\nIn a heavy tail, the average is not the middle, and it is not typical of anything.\n\nThis is the normal condition of urban data. Prices, incomes, building heights, visit counts, firm sizes, the degree of street intersections: city quantities are made by multiplicative processes — percentage markups on percentage premiums on percentage rents — and multiplication breeds skew. A *heavy-tailed* distribution: one whose largest values are not rare accidents but structural members, carrying a fixed share of the total no matter how far out you look. Here the top 1% of listings carries a quarter of all asking revenue. Delete the two €80,018 jokes and the next tier steps into their place.\n\n::: {#cell-fig-tails .cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\"}\nfig, axes = plt.subplots(1, 2, figsize=(9.5, 3.6))\naxes[0].hist(price, bins=120, color=NAVY)\naxes[0].set_title(\"linear euros\", fontsize=11)\naxes[0].set_xlabel(\"€ per night\")\nbins = np.geomspace(price.min(), price.max(), 60)\naxes[1].hist(price, bins=bins, color=NAVY)\naxes[1].set_xscale(\"log\")\naxes[1].set_title(\"log euros\", fontsize=11)\naxes[1].set_xlabel(\"€ per night (log scale)\")\nfor ax in axes:\n    ax.axvline(median, color=GOLD, lw=1.2)\n    ax.axvline(mean, color=BRICK, lw=1.2, ls=\"--\")\ntop = axes[1].get_ylim()[1]\nnote(axes[1], \"median\", (median, 0.80 * top), (58, 0.84 * top))\nnote(axes[1], \"mean\", (mean, 0.62 * top), (1400, 0.70 * top))\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![The same 5,874 nightly prices on a linear axis and a logarithmic one. The linear panel wastes its width on emptiness; the log panel reveals a shape — one bulge, slightly lopsided, with a long right shoulder.](03-statistical-foundations_files/figure-html/fig-tails-output-1.png){#fig-tails}\n:::\n:::\n\n\nThe log scale is not a transformation of the data so much as a correction of the instrument. On a linear axis, the distance from €100 to €200 and the distance from €40,100 to €40,200 are the same distance, which is absurd: the first doubles your rent, the second is a rounding error on a barricade. Plotting on logs says that what matters is *ratio*, and the moment you say it, the distribution turns out to have a shape — roughly the bell of a lognormal, with a right shoulder even the logarithm cannot fully tame. Whether such tails are best read as lognormal or as genuine power laws is a question with a surprising amount of blood on it, and we defer it to @sec-scaling, where city sizes will force the issue. For one market in one city, the practical lesson is smaller: summarize with quantiles, plot on logs, and treat any mean you did not trim with suspicion.\n\n## Describing neighborhoods\n\nThe city's districts make the first demonstration concrete. Amsterdam's planners divide the municipality into 22 *gebieden* — the same areas Inside Airbnb uses — and the listings sort themselves into a portrait:\n\n::: {#cell-fig-districts .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\nby_area = (\n    listings.dropna(subset=[\"price\"])\n    .groupby(\"area\").price\n    .agg(median=\"median\", q1=lambda s: s.quantile(0.25), q3=lambda s: s.quantile(0.75))\n    .join(listings.groupby(\"area\").size().rename(\"n\"))\n    .merge(population, on=\"area\")\n    .assign(per_1k=lambda d: 1000 * d.n / d.population)\n    .sort_values(\"median\")\n)\n\nfig, axes = plt.subplots(1, 2, figsize=(10, 6), sharey=True,\n                         gridspec_kw={\"width_ratios\": [2.2, 1]})\nys = np.arange(len(by_area))\naxes[0].hlines(ys, by_area.q1, by_area.q3, color=NAVY, lw=3, alpha=0.45)\naxes[0].scatter(by_area[\"median\"], ys, color=NAVY, s=28, zorder=3)\naxes[0].set_yticks(ys, by_area.area, fontsize=8.5)\naxes[0].set_xlabel(\"€ per night (median and middle half)\")\naxes[1].barh(ys, by_area.per_1k, color=TEAL, height=0.62)\naxes[1].set_xlabel(\"listings per 1,000 residents\")\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![22 districts, two measures. Left: the middle half of nightly prices (line), with the median marked. Right: listings per thousand residents, the number the housing debate actually turns on. Sorted by median price throughout.](03-statistical-foundations_files/figure-html/fig-districts-output-1.png){#fig-districts}\n:::\n:::\n\n\nRead the two panels against each other. Prices fall from €250 a night in De Pijp–Rivierenbuurt — not, note, in the Centrum, which the tourists believe is the top of the market — to €128 in Bijlmer-Oost, a factor of two across one tram network. Intensity falls much faster: Centrum-West hosts 27 listings for every thousand residents, Bijlmer-Oost 1.3 — a twenty-fold gradient in how much of the neighborhood has been turned over to visitors. Price is what the tourist sees; the right-hand panel is what the city council sees.\n\nA statistical portrait of a place should be built from *robust* summaries: statistics a single absurd value cannot move. Medians, quartiles, trimmed means — estimators with a breakdown point, in the jargon, which is the fraction of the data an adversary must corrupt before the statistic follows them anywhere. The median's is 50%; the mean's is zero. Our €80,018 host corrupted one row and moved the citywide mean by euros; he could not move the median of his own district by a cent.\n\nInequality measures need the same care in the choice of *what* to measure, because the index answers only the question you hand it:\n\n::: {#cell-gini .cell execution_count=5}\n``` {.python .cell-code}\ndef gini(x):\n    \"\"\"Gini coefficient: 0 = perfect equality, 1 = one owner takes all.\"\"\"\n    x = np.sort(np.asarray(x, dtype=float))\n    n = len(x)\n    return (2 * np.arange(1, n + 1) - n - 1).dot(x) / (n * x.sum())\n\nper_host = listings.groupby(\"host_id\").size()\nrevenue_proxy = (listings.price * listings.reviews_per_month).dropna()\npd.Series({\n    \"hosts\": len(per_host),\n    \"share with exactly one listing\": (per_host == 1).mean(),\n    \"Gini, listings per host\": gini(per_host),\n    \"Gini, revenue proxy per listing\": gini(revenue_proxy[revenue_proxy > 0]),\n}).round(3)\n```\n\n::: {#gini .cell-output .cell-output-display execution_count=5}\n```\nhosts                              9201.000\nshare with exactly one listing        0.937\nGini, listings per host               0.118\nGini, revenue proxy per listing       0.614\ndtype: float64\n```\n:::\n:::\n\n\nMeasured by *ownership*, this is one of the most equal platform markets you will find: 94% of hosts run a single listing, and the Gini coefficient over listings-per-host is 0.12 — a decade of registration rules and night caps, visible as a statistic. Measured by *demand*, the same market is lopsided: a Gini of 0.61 over a listing's price-times-bookings, because attention concentrates even where ownership cannot. Neither number is wrong. \"How unequal is Airbnb in Amsterdam?\" is two questions wearing one sentence, and the first job of a descriptive statistician is to take such sentences apart.\n\n## Uncertainty, sampling, and the bootstrap\n\nWhat is the population, when you have scraped the whole platform? Inside Airbnb's file is not a survey of Amsterdam listings; it *is* the Amsterdam listings, every one the scraper could see. The textbook machinery — sample, population, standard error — seems to have nothing to grip. If we say the median price in Bijlmer-Oost is €128, that is not an estimate of the median; it is the median, of all 22 priced listings the district had that week.\n\nAnd yet the number wobbles. Scrape a week earlier or later and a couple of listings appear or vanish, and the median of 22 things moves when any of them does. The population we care about is not the platform on 11 September 2025; it is the *process* generating Amsterdam short-term rents, of which any week's platform is one noisy draw. Under that reading, uncertainty statements are worth making again — and the right tool for making them assumes almost nothing.\n\nThe *bootstrap*: resample your data, with replacement, to the same size; recompute the statistic; repeat a few thousand times; the spread of the recomputed values estimates the spread of the statistic itself. No formula for the standard error of a median in a skewed distribution, no appeal to normality — the data stand in for the process that made them. Of all the tools in this book, I know none with a better ratio of usefulness to assumptions.\n\n::: {#cell-fig-bootstrap .cell execution_count=6}\n``` {.python .cell-code code-fold=\"true\"}\nfig, axes = plt.subplots(2, 1, figsize=(8.5, 4.6), sharex=True)\nfor ax, area, color in zip(axes, [\"De Baarsjes - Oud-West\", \"Bijlmer-Oost\"], [NAVY, BRICK]):\n    x = listings.loc[listings.area == area, \"price\"].dropna().to_numpy()\n    boots = np.median(rng.choice(x, size=(10_000, len(x))), axis=1)\n    lo, hi = np.percentile(boots, [2.5, 97.5])\n    ax.hist(boots, bins=60, color=color, alpha=0.85)\n    ax.axvspan(lo, hi, color=color, alpha=0.12, lw=0)\n    ax.set_title(f\"{area} — n = {len(x)}, 95% interval €{lo:.0f}–€{hi:.0f}\", fontsize=10.5)\n    ax.set_yticks([])\naxes[1].set_xlabel(\"bootstrap median, € per night\")\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![Ten thousand bootstrap medians for a large district and a tiny one, on a shared axis. De Baarsjes–Oud-West (992 priced listings) knows its median to about ±€10; Bijlmer-Oost (22) is sure of nothing within a €90 window — and the gaps in its histogram are the prices of individual apartments.](03-statistical-foundations_files/figure-html/fig-bootstrap-output-1.png){#fig-bootstrap}\n:::\n:::\n\n\nThe picture carries the whole argument. The big district's medians pile into a tidy near-normal heap twenty euros wide. The small district's are a comb: with 22 observations the resampled median can only land on a handful of actual prices, so the distribution has teeth, and the 95% interval spans €96 to €185 — *we do not know the going rate in Bijlmer-Oost to within a factor of two*. Any table of neighborhood statistics that prints both districts to the same confident decimal place is lying by typography. Hold the thought; the chapter's final section is about what to do with it.\n\nOne caution before moving on. The bootstrap quantifies sampling wobble and nothing else. The 44% of listings with no displayed price, the scraper's blind spots, the hosts who list on other platforms entirely — no amount of resampling sees any of that. The bootstrap tells you how much your statistic would vary if the process re-dealt the same kind of data; it is silent about whether the data are the right data. Statistics has a vocabulary for the first problem; the second is fieldwork.\n\n## Comparison and testing\n\nDo prices really differ between districts, or are we reading tea leaves in the wobble? For two districts, the disciplined way to ask is embarrassingly direct. Take De Pijp–Rivierenbuurt (median €250) and Westerpark (€214.50): if district membership made no difference, the labels would be arbitrary — so shuffle them. Pool the prices, deal them back at random, recompute the gap in medians, and repeat until you know what gaps pure label-shuffling produces.\n\n::: {#cell-permutation .cell execution_count=7}\n``` {.python .cell-code}\na = listings.loc[listings.area == \"De Pijp - Rivierenbuurt\", \"price\"].dropna().to_numpy()\nb = listings.loc[listings.area == \"Westerpark\", \"price\"].dropna().to_numpy()\nobserved = np.median(a) - np.median(b)\n\npooled = np.concatenate([a, b])\nshuffled = np.array([\n    np.median(s[: len(a)]) - np.median(s[len(a):])\n    for s in (rng.permutation(pooled) for _ in range(10_000))\n])\np_value = (np.abs(shuffled) >= abs(observed)).mean()\nf\"observed gap €{observed:.1f}; in 10,000 shuffles, a gap this large appeared {int(p_value * 10_000)} times\"\n```\n\n::: {#permutation .cell-output .cell-output-display execution_count=7}\n```\n'observed gap €35.5; in 10,000 shuffles, a gap this large appeared 0 times'\n```\n:::\n:::\n\n\nA *p-value*: the share of label-shuffles that produce a difference at least as large as the real one. Ten thousand shuffles never managed €35.50, so the gap is no accident of wobble — De Pijp is dearer than Westerpark in a sense the data can defend. Notice what the permutation test did *not* require: no normality, no equal variances, no formula remembered from a course. The shuffle is the null hypothesis, performed rather than assumed.\n\nNow the trap. With 22 districts there are 231 pairs, and testing them all is exactly the kind of thing a loop makes effortless:\n\n::: {#cell-pairwise .cell execution_count=8}\n``` {.python .cell-code}\nfrom itertools import combinations\nfrom scipy.stats import mannwhitneyu\nfrom statsmodels.stats.multitest import multipletests\n\ngroups = {a: g.dropna().to_numpy() for a, g in listings.groupby(\"area\").price if len(g.dropna()) >= 20}\npairs = list(combinations(groups, 2))\npvals = np.array([mannwhitneyu(groups[x], groups[y]).pvalue for x, y in pairs])\ngaps = np.array([abs(np.median(groups[x]) - np.median(groups[y])) for x, y in pairs])\n\nraw = pvals < 0.05\nbonf = multipletests(pvals, method=\"bonferroni\")[0]\nbh = multipletests(pvals, method=\"fdr_bh\")[0]\n\n# Control experiment: the same 231 tests where district labels mean nothing\npool = listings.price.dropna().to_numpy()\nnoise = np.array([\n    mannwhitneyu(rng.choice(pool, 200), rng.choice(pool, 200)).pvalue\n    for _ in range(len(pairs))\n])\npd.Series({\n    \"pairs tested\": len(pairs),\n    \"significant at p < .05, uncorrected\": int(raw.sum()),\n    \"after Bonferroni\": int(bonf.sum()),\n    \"after Benjamini–Hochberg\": int(bh.sum()),\n    \"uncorrected 'findings' with a gap under €15\": int((raw & (gaps < 15)).sum()),\n    \"uncorrected 'findings' on label-shuffled noise\": int((noise < 0.05).sum()),\n})\n```\n\n::: {#pairwise .cell-output .cell-output-display execution_count=8}\n```\npairs tested                                      231\nsignificant at p < .05, uncorrected               164\nafter Bonferroni                                   96\nafter Benjamini–Hochberg                          159\nuncorrected 'findings' with a gap under €15         2\nuncorrected 'findings' on label-shuffled noise      8\ndtype: int64\n```\n:::\n:::\n\n\nOn the real data, 164 pairs come up significant uncorrected, 96 survive Bonferroni's heavy hand, 159 survive Benjamini–Hochberg's lighter one — Amsterdam's districts genuinely differ, and no correction makes that go away. The row to memorize is the control: run the same 231 tests where the labels mean nothing and the 5% level still hands you a fistful of \"discoveries\" — eight on this draw, about a dozen in expectation — each wearing the same confident p-value as the real thing. A second, quieter trap: two of the genuine findings separate districts whose medians sit less than €15 apart — detectable because large samples make even trivia detectable, and beneath an economist's notice. A p-value measures surprise, not size. The question that matters — *how different?* — is answered by the gap itself, with a bootstrap interval around it; the test only certifies that the gap is no artifact of shuffling. Significance is the entry ticket, never the exhibit.\n\n## Regression I: pricing the city\n\nDescription ends and explanation begins with a question of attribution. A canal-view apartment rents dear — but is that the view, or is it that canal views come attached to the seventeenth-century center, large windows, and hosts who have learned what photographs sell? *Hedonic regression*: the workhorse method that prices a good by decomposing it into priced attributes, treating every listing as a bundle — beds, baths, room type, reputation, place — and asking what the market pays for each element while the others stand still.\n\nThe platform hands us the view variable directly: 996 listings claim \"Canal view\" among their amenities (582 of them priced and complete), and 1,011 claim the vaguer \"Waterfront\". We regress the *logarithm* of price — heavy tail, multiplicative city — so coefficients read as percentage premiums. And we fit the model twice, first pretending location does not exist, because the mistake is instructive:\n\n::: {#cell-hedonic .cell execution_count=9}\n``` {.python .cell-code code-summary=\"Two hedonic models: attributes only, then attributes + district\"}\nimport statsmodels.formula.api as smf\n\nh = listings.dropna(subset=[\"price\"]).copy()\nh = h[h.price.between(30, 2000)]              # drop the barricades and a few €1 jokes\nh[\"log_price\"] = np.log(h.price)\nh[\"canal_view\"] = h.amenities.str.contains(\"Canal view\", na=False)\nh[\"waterfront\"] = h.amenities.str.contains(\"Waterfront\", na=False)\nh[\"bathrooms_n\"] = h.bathrooms_text.str.extract(r\"([\\d.]+)\").astype(float).fillna(1)\nh = h.dropna(subset=[\"bedrooms\", \"accommodates\", \"review_scores_rating\"])\n\nFORM = (\"log_price ~ C(room_type, Treatment('Private room')) + accommodates\"\n        \" + bedrooms + bathrooms_n + review_scores_rating + canal_view + waterfront\")\nm_naive = smf.ols(FORM, data=h).fit()\nm_full = smf.ols(FORM + \" + C(area)\", data=h).fit()\n\ndef premium(model, term):\n    b, (lo, hi) = model.params[term], model.conf_int().loc[term]\n    return f\"{np.expm1(b):+.1%}  ({np.expm1(lo):+.1%} to {np.expm1(hi):+.1%})\"\n\npd.DataFrame({\n    name: {\n        \"canal view\": premium(m, \"canal_view[T.True]\"),\n        \"waterfront\": premium(m, \"waterfront[T.True]\"),\n        \"R²\": round(m.rsquared, 3),\n    }\n    for name, m in [(\"attributes only\", m_naive), (\"+ district\", m_full)]\n}).T\n```\n\n::: {#hedonic .cell-output .cell-output-display execution_count=9}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>canal view</th>\n      <th>waterfront</th>\n      <th>R²</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>attributes only</th>\n      <td>+27.5%&nbsp;&nbsp;(+22.8% to +32.4%)</td>\n      <td>-5.4%&nbsp;&nbsp;(-8.3% to -2.5%)</td>\n      <td>0.44</td>\n    </tr>\n    <tr>\n      <th>+ district</th>\n      <td>+13.7%&nbsp;&nbsp;(+9.8% to +17.7%)</td>\n      <td>-1.0%&nbsp;&nbsp;(-3.7% to +1.8%)</td>\n      <td>0.549</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nWithout location, a canal view appears to be worth 28% a night. With the 22 district dummies in the model, it is worth 13.7% — confidence interval 10% to 18% — on an otherwise identical listing *in the same district*. Half of the apparent premium was never the water; it was the postcode that tends to come with water, an omitted variable doing what omitted variables do, which is to launder one cause into another's coefficient. The laundering runs both directions: in the location-blind model, \"Waterfront\" carries a *significant* 5% penalty; add the dummies and it evaporates to −1%, interval straddling zero. Whatever the word means to the hosts who tick it — moorings, docklands, a glimpse of the IJ — the market, holding place and attributes constant, pays nothing for it. The specific claim earns 14%; the vague one earns silence. The market pays for the specific claim and ignores the vague one, a finding that will surprise no one who has written a property listing. The rest of the model behaves as sense demands — each additional guest of capacity adds about 14%, a bathroom 11%, an entire home runs 51% above a private room, and the district premiums span −20% to +67% from the Bijlmer to Centrum-West.\n\n::: {#cell-fig-resid-map .cell execution_count=10}\n``` {.python .cell-code code-fold=\"true\"}\nres = h.assign(naive=m_naive.resid, full=m_full.resid)\ngres = areas.merge(\n    res.groupby(\"area\")[[\"naive\", \"full\"]].mean().reset_index(),\n    left_on=\"neighbourhood\", right_on=\"area\",\n)\nfig, axes = plt.subplots(1, 2, figsize=(10, 4.6))\nfor ax, col, title in [(axes[0], \"naive\", \"attributes only\"), (axes[1], \"full\", \"+ district dummies\")]:\n    gres.plot(column=col, cmap=\"book_div\", vmin=-0.5, vmax=0.5, ax=ax,\n              edgecolor=\"#dedacc\", linewidth=0.3, legend=(col == \"full\"))\n    ax.set_axis_off()\n    ax.set_title(title, fontsize=11)\nfig.suptitle(\"Where the model is wrong\", x=0.01, ha=\"left\", fontsize=13, fontweight=\"bold\")\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![Mean regression residual by district. Left: the attributes-only model misses with a geography — under-predicting the center by 20% and over-predicting the far southeast by more. Right: with district dummies the district means are zero by construction; the dummies did not explain the geography so much as confiscate it.](03-statistical-foundations_files/figure-html/fig-resid-map-output-1.png){#fig-resid-map}\n:::\n:::\n\n\nThe left map is the chapter's cliff-hanger. Fit a model with no notion of place, and place reappears, uninvited, in the residuals: every error wears an address, the center systematically under-predicted, the periphery over-predicted, the pattern as legible as a transit map. District dummies buy the pattern back at the cost of 21 coefficients and no understanding — they assert that the 22 areas are 22 unrelated islands, when the left map plainly shows a *gradient*, premiums decaying smoothly from the canals outward, indifferent to administrative borders. Within each island the texture remains, and listings near a district's fashionable edge still embarrass the model. What the residuals are whispering is that space is not a category; it is a surface. Giving that intuition a formal vocabulary — weights, lags, spatially correlated errors — is the business of *Regression II*, in @sec-spatial.\n\n## Bayesian thinking: borrowing strength\n\nReturn now to the problem the bootstrap exposed and the chapter has twice postponed: Bijlmer-Oost, 22 priced listings, median known only to within a factor of two. The city has many such districts — small, peripheral, and exactly where the housing debate most needs numbers. Print the raw means and the smallest districts will routinely post the most extreme figures, for the same reason small hospitals post both the best and worst mortality rates: noise scales as one over the square root of n, and somebody has to be in the tail.\n\nThe Bayesian instinct is that a district is not an island of data but a member of a city, and the city's other districts tell you roughly what districts are like. *Partial pooling*: estimate each district as a weighted compromise between its own mean and the city's, weighting by how much each is to be trusted — the district's data in proportion to its size, the city's grand mean in proportion to how alike districts tend to be. Districts with thousands of listings keep their own counsel; districts with twenty borrow strength from everyone else.\n\n::: {#cell-shrinkage .cell execution_count=11}\n``` {.python .cell-code code-summary=\"Normal-normal partial pooling, by hand\"}\nlp = h.groupby(\"area\").log_price.agg([\"mean\", \"var\", \"size\"])\ngrand = h.log_price.mean()\nbetween = max(lp[\"mean\"].var() - (lp[\"var\"] / lp[\"size\"]).mean(), 1e-9)\nweight = between / (between + lp[\"var\"] / lp[\"size\"])\nlp[\"pooled\"] = weight * lp[\"mean\"] + (1 - weight) * grand\nlp[\"weight\"] = weight\nlp.sort_values(\"size\")[[\"size\", \"mean\", \"pooled\", \"weight\"]].head(5).round(3)\n```\n\n::: {#shrinkage .cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>size</th>\n      <th>mean</th>\n      <th>pooled</th>\n      <th>weight</th>\n    </tr>\n    <tr>\n      <th>area</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Bijlmer-Oost</th>\n      <td>20</td>\n      <td>4.927</td>\n      <td>5.035</td>\n      <td>0.773</td>\n    </tr>\n    <tr>\n      <th>Gaasperdam - Driemond</th>\n      <td>28</td>\n      <td>4.766</td>\n      <td>4.890</td>\n      <td>0.807</td>\n    </tr>\n    <tr>\n      <th>Osdorp</th>\n      <td>35</td>\n      <td>5.042</td>\n      <td>5.082</td>\n      <td>0.890</td>\n    </tr>\n    <tr>\n      <th>Bijlmer-Centrum</th>\n      <td>35</td>\n      <td>4.875</td>\n      <td>4.931</td>\n      <td>0.895</td>\n    </tr>\n    <tr>\n      <th>De Aker - Nieuw Sloten</th>\n      <td>37</td>\n      <td>5.050</td>\n      <td>5.103</td>\n      <td>0.852</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEight lines, no special library, and the machinery is visible: `between` estimates how much district means genuinely differ (τ ≈ 0.21 on the log scale — about 24% from a typical district to the city mean); the weight on a district's own data is its signal share, between-variance over between-plus-noise. De Baarsjes, with a thousand listings, keeps 99% of its own mean. Gaasperdam-Driemond, with 28, keeps 81% and concedes the rest to Amsterdam at large, sliding 13% toward the middle.\n\n::: {#cell-fig-shrinkage .cell execution_count=12}\n``` {.python .cell-code code-fold=\"true\"}\nfig, ax = plt.subplots(figsize=(8.5, 5.2))\norder = lp.sort_values(\"mean\")\nax.axvline(grand, color=GOLD, lw=1.1, ls=\"--\")\nfor y, (name, row) in enumerate(order.iterrows()):\n    moved = abs(row[\"pooled\"] - row[\"mean\"]) > 0.02\n    ax.annotate(\"\", xy=(row.pooled, y), xytext=(row[\"mean\"], y),\n                arrowprops={\"arrowstyle\": \"->\", \"color\": BRICK if moved else \"#c9cdd2\",\n                            \"lw\": 1.4 if moved else 0.9})\n    ax.scatter(row[\"mean\"], y, s=8 + row[\"size\"] / 12,\n               color=NAVY, alpha=0.85, zorder=3)\nax.set_yticks(range(len(order)), order.index, fontsize=8.5)\nax.set_xlabel(\"mean log price  (raw → partially pooled)\")\nnote(ax, \"the city mean\", (grand, 20.3), (5.62, 21.2))\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![Partial pooling in one picture: each district's raw mean log-price (left end) and its pooled estimate (right end), point area proportional to listing count. The big districts barely move; the small ones are reeled toward the city mean — most strongly when they sat furthest out, which is exactly when raw means deserve the least belief.](03-statistical-foundations_files/figure-html/fig-shrinkage-output-1.png){#fig-shrinkage}\n:::\n:::\n\n\nThis is shrinkage, and the name undersells it. Nothing about a small district's data was wrong; what shrinks is our willingness to take 22 observations at their word when 5,000 neighbors are available as context. The estimate that results is biased — deliberately, toward the city — and in exchange its error shrinks too: across many small districts, pooled estimates land closer to next year's truth than raw means do, a trade first made precise by Stein in 1956 and rediscovered by every analyst who has ranked neighborhoods on thin data. The full Bayesian apparatus — priors made explicit, posteriors propagated, hierarchies deeper than two levels — extends this logic and returns in the chapters where it earns its complexity. The instinct is what matters here, and it is the same instinct the whole chapter has been training: a number from a city is never alone. It arrives with a tail, a neighborhood, a denominator, a process that made it — and it is read properly only in their company.\n\nThe next chapter abandons explanation for prediction and grades itself the hard way, on data it has never seen. The discipline learned here travels: the heavy tails go with us, the suspicion of confident decimals goes with us, and Regression I waits for its sequel.\n\n::: {.callout-note}\n## The contested platform city\n\nNo European city has fought its short-term rental market longer or in more detail than Amsterdam. The sequence of regulation reads like a dose-escalation trial: a 60-night annual cap on entire-home rentals (2014, the first of its kind), halved to 30 nights (2019); a mandatory registration number for every listing (2021), without which platforms must refuse the advertisement; attempted outright bans in three center districts (2020), partly struck down in court, re-imposed in revised form. The dataset shows the regime's fingerprints everywhere: 94% single-listing hosts where less-regulated cities grow multi-listing empires, 778 listings marked \"Exempt\", a `license` column of government-issued codes — including, the attentive reader will find, a few dozen that read `ABCD 1234 AB12 89EF`, the form's *example* number, copied in by hosts with more compliance than attention. Exercise 4 sends you after them.\n\nThe scholarly fight runs on parallel tracks. Wachsmuth and Weisler's \"rent gap\" studies argue that platforms let landlords harvest tourist rents from housing stock, raising rents citywide; other economists measure the effect per listing and find it real but small. Both sides argue from data like this chapter's — which is why Inside Airbnb exists at all: it began as one activist's scraping project (Murray Cox, from 2015) to give the debate numbers the platform declined to publish. Every figure in this chapter stands on that act of civic data collection. The methods are neutral; the existence of the dataset is not.\n:::\n\n## Exercises {.unnumbered}\n\n1. **The other inequality.** Compute the Gini coefficient of the revenue proxy (price × reviews per month) *within* each district, and rank districts by it. Does inequality among listings run higher in the center or the periphery? Offer a mechanism, then find one further statistic that could distinguish your mechanism from one alternative.\n2. **The museum premium, properly.** \"Prices spike near the museums\" is folk wisdom on every Amsterdam forum. Test it: compute each listing's distance to the Rijksmuseum, compare price across distance bands, then add the hedonic controls from Regression I. How much of the folk premium survives? State what your test cannot distinguish (museum proximity from Zuid postcodes, for a start).\n3. **Shrinkage you can defend.** Repeat the partial-pooling estimate for the share of superhosts per district instead of mean log price (a proportion needs a slightly different noise variance — derive it). Which district moves most, and why is that the right district to move?\n4. **The license landmine.** Find every listing whose registration number is a copied example or otherwise implausible, and estimate what share of \"registered\" listings they represent. Decide, and defend, whether they belong in the regression sample — then check whether their inclusion changes any coefficient by more than its confidence interval.\n5. **Tail forensics.** Fit a lognormal to the priced listings by maximum likelihood and plot its CCDF against the empirical one on log-log axes. Where does the fit fail, by how much, and how many listings live in the failure region? Keep your answer; @sec-scaling will ask the same question about entire cities.\n\n## Further reading {.unnumbered}\n\n- **Gelman & Hill, *Data Analysis Using Regression and Multilevel/Hierarchical Models* (2007).** The standard course on partial pooling and why it works; chapters 11–12 are this chapter's final section, grown up.\n- **Efron & Tibshirani, *An Introduction to the Bootstrap* (1993).** The source. Readable, surprisingly funny, and still the best statement of the resampling worldview.\n- **Wasserstein & Lazar, \"The ASA's Statement on p-Values\" (2016).** The professional society's own warning label, with the discussion that followed; required before publishing a significance star.\n- **Wachsmuth & Weisler, \"Airbnb and the Rent Gap\" (2018).** The most-cited case that platform rentals reshape housing markets; read alongside a platform-side response and the data you now know how to check.\n- **Inside Airbnb, \"About the Data\" (insideairbnb.com).** The methodology notes for this chapter's anchor: what the scraper sees, what it cannot, and the assumptions behind every derived field.\n\n",
    "supporting": [
      "03-statistical-foundations_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}